# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Flavio Vinicius Diniz de Figueiredo
email: 
description: > # this means to ignore newlines until "baseurl:"
  Flavio Figueiredo is a Computer Science Professor @ UFMG
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://flaviovdf.github.io." # the base hostname & protocol for your site
twitter_username: flaviovdf
github_username:  flaviovdf

# Build settings
markdown: kramdown
